/* table adresse */
INSERT INTO ADRESSE (IDADRESSE, PORTE, RUE, APPARTEMENT, CODEPOSTAL, LOCALITE, PROVINCE, PAYS) 
	         VALUES ('1', '3135', 'bedford', '204', 'h3s1g4', 'montreal', 'quebec', 'canada');
INSERT INTO ADRESSE (IDADRESSE, PORTE, RUE, APPARTEMENT, CODEPOSTAL, LOCALITE, PROVINCE, PAYS) 
	         VALUES ('2', '3140', 'hudson', '6', 'H3SA8T', 'montreal', 'quebec', 'canada');
	
/* table client */
INSERT INTO CLIENT (IDCLIENT, NOM, PRENOM, DATENAISSANCE, IDADRESSE, COURRIEL, TELEPHONE) 
	        VALUES ('1', 'semlani', 'selma', '2019-09-26 07:43:50.0', '1', 'selma@gmail.com', '876544');
INSERT INTO CLIENT (IDCLIENT, NOM, PRENOM, DATENAISSANCE, IDADRESSE, COURRIEL, TELEPHONE) 
	        VALUES ('2', 'elbey', 'mohamed', '2019-09-26 00:00:00.0', '2', 'selma@gmail.com', '876544');

/* table compte */
INSERT INTO COMPTE (NUMCOMPTE, NIP, SOLDE, TYPECOMPTE, IDCLIENT, LIMITEOPERATION) 
	        VALUES ('111111', '111', 5000, 'cheque', '1', 1000);	
INSERT INTO COMPTE (NUMCOMPTE, NIP, SOLDE, TYPECOMPTE, IDCLIENT, LIMITEOPERATION) 
	        VALUES ('222222', '222', 3000, 'epargne', '2', 1500);	
			
/* table beneficiaire */
INSERT INTO BENEFICIAIRE (NOMBENEFICIAIRE, TELEPHONE, IDADRESSE) 
	              VALUES ('bell', '77666', '1');
INSERT INTO BENEFICIAIRE (NOMBENEFICIAIRE, TELEPHONE, IDADRESSE) 
	              VALUES ('videotron', '86543', '2');
				  
/* table typeoperation */
INSERT INTO TYPEOPERATION (CODEOPERATION, DESIGNATION) 
	               VALUES ('R', 'retrait');
INSERT INTO TYPEOPERATION (CODEOPERATION, DESIGNATION) 
	               VALUES ('D', 'depot');
INSERT INTO TYPEOPERATION (CODEOPERATION, DESIGNATION) 
	               VALUES ('P', 'payement facture');
INSERT INTO TYPEOPERATION (CODEOPERATION, DESIGNATION) 
	               VALUES ('V', 'virement');

/* table operation */
INSERT INTO OPERATION (NUMOPERATION, DATEOPERATION, MONTANTOPERATION, TYPEOPERATION, NUMCOMPTE, NOMBENEFICIAIRE) 
	           VALUES (32, '2019-10-14 21:43:54.0', 1000, 'R', '111111', NULL);
INSERT INTO OPERATION (NUMOPERATION, DATEOPERATION, MONTANTOPERATION, TYPEOPERATION, NUMCOMPTE, NOMBENEFICIAIRE) 
	           VALUES (33, '2019-10-14 21:44:14.0', 1000, 'D', '111111', NULL);	
INSERT INTO OPERATION (NUMOPERATION, DATEOPERATION, MONTANTOPERATION, TYPEOPERATION, NUMCOMPTE, NOMBENEFICIAIRE) 
	           VALUES (34, '2019-10-14 21:44:22.0', 500, 'P', '111111', NULL);			   
